services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "54320:5432"