services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=root
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      - "54320:5432"
    networks:
      - app-network

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://root:postgres@db:5432/medusa?ssl_mode=disable
    networks:
      - app-network

networks:
  app-network:
    driver: bridge